apiVersion: core.choreo.dev/v1beta1
kind: Component
metadata:
  name: essay-grader
  description: A rubric essay grading tool using Gemini AI
spec:
  type: service
  port: 5000
  inbound:
    - path: /grade-essay
      method: POST
      summary: Grade an essay based on rubric
  env:
    - name: GEMINI_API_KEY
      valueFrom: secret
    - name: PORT
      value: "5000"
  build:
    dockerfile: |
      FROM node:24-alpine
      WORKDIR /app
      COPY package*.json ./
      RUN npm ci --only=production
      COPY . .
      EXPOSE 5000
      CMD ["npm", "start"]
  dependencies:
    - name: nodejs
      version: "24"